apiVersion: v1
kind: Service
metadata:
  name: faster-whisper
  namespace: ai
  labels:
    app: faster-whisper
    app.kubernetes.io/name: faster-whisper
    app.kubernetes.io/component: stt
spec:
  type: ClusterIP
  selector:
    app: faster-whisper
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
