apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui
  annotations:
    cert-manager.io/cluster-issuer: vx-home-ca-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ai.vx.home
    secretName: openwebui-tls
  rules:
  - host: ai.vx.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openwebui
            port:
              number: 80
