apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - configmap-servers.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: pgadmin
  app.kubernetes.io/component: admin-ui
