apiVersion: apps/v1
kind: Deployment
metadata:
  name: kokoro
spec:
  template:
    spec:
      nodeSelector:
        gpu: "small"
      containers:
      - name: kokoro
        resources:
          limits:
            nvidia.com/gpu: 1
