apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data
  namespace: ai
  labels:
    app: openwebui
    app.kubernetes.io/name: openwebui
    app.kubernetes.io/component: frontend
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 50Gi
