apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - ../../../../base/kokoro

commonLabels:
  app.kubernetes.io/part-of: vx-home-ai-stack

patches:
  # GPU and node selector
  - path: patches/gpu.yaml
    target:
      kind: Deployment
      name: kokoro
