apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-node
  namespace: rook-ceph-external
type: kubernetes.io/rook
stringData:
  adminID: cephfs-csi
  adminKey: AQCpl1VpuwsMCxAA4BfD9typCaMeyovcJ1i90A==
